apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: radhikari
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/radhikari-harbor-project/db:971c881-c2cd402
        ports:
        - containerPort: 5432
